// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5Q7hDElElWGlderT86Y1ymOoRFfmx-cg',
    appId: '1:401212845335:android:765d25fc957dfc95581b52',
    messagingSenderId: '401212845335',
    projectId: 'quickstartflutter',
    databaseURL: 'https://quickstartflutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quickstartflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACvbBX_2nzbcZN1RJ9LiFgVnIm3Ov7OPY',
    appId: '1:401212845335:ios:f8cdefc25d57e9b9581b52',
    messagingSenderId: '401212845335',
    projectId: 'quickstartflutter',
    databaseURL: 'https://quickstartflutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quickstartflutter.appspot.com',
    iosClientId: '401212845335-ji9e77pkoli1mr3u59hd94vkhqpbaes8.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickstartFlutter',
  );
}
